### ISSUE TITLE
Question: Packages not published?

### ISSUE THREAD

**Issue by kmcgill88** [juancastillo0/leto#3]
I feel like I'm missing something. The README install instructions say add these dependencies but it doesn't appear those packages are published to pub.dev? 😁

```yaml
dependencies:
  leto_schema: ^0.0.1
  leto: ^0.0.1
  leto_shelf: ^0.0.1
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  # Not nessary for the server, just for testing it
  http: ^1.0.0

dev_dependencies:
  # Only if you use code generation
  leto_generator: ^0.0.1
  build_runner: ^2.0.0
```

**Comment by juancastillo0** [comment]
Yes, the package is not published at the moment, sorry for not being explicit enough in the readme. You can use it directly from git or you could also clone the repository locally and use relative dependencies like this [example](https://github.com/juancastillo0/leto/blob/df12485d0edc4e2d1016a581113c3411922137c5/chat_example/server/pubspec.yaml). It will be published, I want to stabilize some apis first and there where some PRs in the gql package that where necessary before publishing.

You could try this if you don't want to clone the repo locally:

```yaml
dependency_overrides:
  leto_generator:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_generator
  leto:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto
  leto_schema:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_schema
  leto_shelf:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_shelf
```

Let me know if you need more help!

**Comment by kmcgill88** [comment]
Any roadmap to get this published? Also, are you in the [GraphQL Dart Discord](https://discord.gg/vYtZuAjrVr)?

**Comment by juancastillo0** [comment]
Hi thanks, I joined the Discord and just publish the packages. You can use all of them with the `^0.0.1-dev.1` version:

```
dependencies:
  leto_schema: ^0.0.1-dev.1
  leto: ^0.0.1-dev.1
  leto_shelf: ^0.0.1-dev.1
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  # Not nessary for the server, just for testing it
  http: ^1.0.0

dev_dependencies:
  # Only if you use code generation
  leto_generator: ^0.0.1-dev.1
  build_runner: ^2.0.0
```
